### ISSUE TITLE
Object reference chain is too long when using --dynamic option in angular app

### ISSUE THREAD

**Issue by vivek-saurabh** [Munter/subfont#129]
Hi,
Thanks for building such a beautiful project.

- Angular 9.0.6
- Ubuntu 18.04
- Subfont 5.2.2
Command I run: subfont path/index.html -o path/browser/ --dynamic=true.
I get the following error every time.
`Error: Protocol error (Runtime.callFunctionOn): Object reference chain is too long
    at /home/ubuntu/.nvm/versions/node/v12.16.2/lib/node_modules/subfont/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:208:63
    at Promise._execute (/home/ubuntu/.nvm/versions/node/v12.16.2/lib/node_modules/subfont/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/home/ubuntu/.nvm/versions/node/v12.16.2/lib/node_modules/subfont/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/home/ubuntu/.nvm/versions/node/v12.16.2/lib/node_modules/subfont/node_modules/bluebird/js/release/promise.js:103:10)
    at CDPSession.send (/home/ubuntu/.nvm/versions/node/v12.16.2/lib/node_modules/subfont/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:207:16)
    at JSHandle.jsonValue (/home/ubuntu/.nvm/versions/node/v12.16.2/lib/node_modules/subfont/node_modules/puppeteer-core/lib/cjs/puppeteer/common/JSHandle.js:156:49)
    at transferResults (/home/ubuntu/.nvm/versions/node/v12.16.2/lib/node_modules/subfont/lib/HeadlessBrowser.js:5:34)
    at HeadlessBrowser.tracePage (/home/ubuntu/.nvm/versions/node/v12.16.2/lib/node_modules/subfont/lib/HeadlessBrowser.js:122:12)
    at async subsetFonts (/home/ubuntu/.nvm/versions/node/v12.16.2/lib/node_modules/subfont/lib/subsetFonts.js:787:32)
    at async subfont (/home/ubuntu/.nvm/versions/node/v12.16.2/lib/node_modules/subfont/lib/subfont.js:229:24)
`
Can you please help me out with this issue

**Comment by papandreou** [comment]
That's interesting!

Just to rule out that it's a problem with your local puppeteer install, could you try with a very simple "Hello world" webpage as well?

Otherwise, could you grant me access to copy of the site that you're running subfont on? Then I can dive in.
