### ISSUE TITLE
Cannot read property 'removeChild' of undefined

### ISSUE THREAD

**Issue by thescientist13** [Munter/subfont#24]
Just wanted to say I saw your talk @ JSConf on YouTube and thought it was great!  Thanks so much, I've been looking for something [exactly like this](https://github.com/ProvidenceGeeks/website-frontend/issues/152) and getting mixed results with existing solutions.

### Overview
I installed **subfont** and related **Python** dependencies, generated a build with **webpack** for my **React** app, and ran the `subfont` CLI, but got this error:
```shell
$ ./node_modules/.bin/subfont ./build/index.html -i
Guessing --root from input files: file:///Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/build/
 ✔ 0.037 secs: logEvents
 ✔ 0.135 secs: loadAssets
 ✔ 0.951 secs: populate
 ✔ 0.012 secs: populate
 ✔ 0.011 secs: populate
TypeError: subsetFonts transform: Cannot read property 'removeChild' of undefined
    at CssImport.detach (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/assetgraph/lib/relations/CssImport.js:76:21)
    at asyncLoadStyleRelationWithFallback (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/assetgraph/lib/transforms/subsetFonts.js:216:20)
    at subsetFonts (/Users/owenbuckley/Workspace/pvdgeeks.org/website-frontend/node_modules/assetgraph/lib/transforms/subsetFonts.js:975:11)
    at <anonymous>
```

I am using node v8.9.4 for reference
```shell
$ node -v
v8.9.4
```

Although I am building with **webpack**, I am using [**critical**](https://github.com/addyosmani/critical) to generate above the fold inlined critical CSS which has the Google Fonts URL in it, so hopefully this should be compatible?  (I am also hosting the site statically with S3 / CloudFront).

For context, here is what my bundled _index.html_ looks like
```html
<!DOCTYPE html>
<html lang="en">

  <head>
    <base href="/">
    <title>Providence Geeks</title>  
    <meta charset="utf-8">
    <meta name="description" content="The goal of Providence Geeks is to help Rhode Island’s digital innovators connect, collaborate, and ultimately make the City-State and its geeks info-technology leaders.">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="Providence Geeks"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="theme-color" content="#1a2930"><link rel="apple-touch-startup-image" href="icon_1024x1024.915638a2e87880eaf307a0baf1abb24e.png"><link rel="apple-touch-icon" sizes="512x512" href="icon_512x512.182f900ea4c1bf1883c11413b67364df.png"><link rel="apple-touch-icon" sizes="167x167" href="icon_167x167.7a223e8ceb81b340d9099a64df02e34a.png"><link rel="apple-touch-icon" sizes="180x180" href="icon_180x180.ae62ab86f45f19c58e995096c11bc9f7.png"><link rel="apple-touch-icon" sizes="152x152" href="icon_152x152.be7c2455346e0d37b432eb67ba150122.png"><link rel="apple-touch-icon" sizes="120x120" href="icon_120x120.a13fab9321c4d18b10fd0f77e80ea5b2.png"><link rel="apple-touch-icon" sizes="87x87" href="icon_87x87.04983c9d18d15515f3f4075be15ebbcc.png"><link rel="apple-touch-icon" sizes="80x80" href="icon_80x80.1e1e27f7d5dfda91b748947e59c20283.png"><link rel="apple-touch-icon" sizes="72x72" href="icon_72x72.d867a890d58b552d4f30996f52abf51b.png"><link rel="apple-touch-icon" sizes="60x60" href="icon_60x60.a4bea2cdeb17d15721bfb280f1505905.png"><link rel="apple-touch-icon" sizes="58x58" href="icon_58x58.36090288ae1be803e6dd4b5d6d19dfeb.png"><link rel="apple-touch-icon" sizes="48x48" href="icon_48x48.09614ee52de1df6fafeab1f16ad211a6.png"><link rel="apple-touch-icon" sizes="40x40" href="icon_40x40.0c1ff8367f50dc25320d1e304d70e441.png"><link rel="manifest" href="manifest.7fa4bf81bf98eff860156d48681ab0d9.json"><meta name="mobile-web-app-capable" content="yes"><meta name="theme-color" content="#bcbfc2"><meta name="application-name" content="Providence Geeks"><link rel="icon" type="image/png" sizes="32x32" href="icons/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="icons/favicon-16x16.png"><link rel="shortcut icon" href="icons/favicon.ico">
<style type="text/css">
    @import url(//fonts.googleapis.com/css?family=Josefin+Sans:300,400,400i,700|Josefin+Slab:300,400,400i,700);*,:after,:before{box-sizing:border-box}html{font-family:sans-serif;line-height:1.15;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}body{margin:0;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,sans-serif;font-size:1rem;font-weight:400;line-height:1.5;color:#212529;text-align:left;background-color:#fff}::-webkit-file-upload-button{font:inherit;-webkit-appearance:button}@-ms-viewport{width:device-width}html{box-sizing:border-box;-ms-overflow-style:scrollbar}*,:after,:before{box-sizing:inherit}body{font-family:Josefin Sans,sans-serif}
  </style>
  <link href="0.ca7c27d106cde55c9e35.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link href="0.ca7c27d106cde55c9e35.css" rel="stylesheet"></noscript>
  <script>!function(t){"use strict";t.loadCSS||(t.loadCSS=function(){});var e=loadCSS.relpreload={};if(e.support=function(){var e;try{e=t.document.createElement("link").relList.supports("preload")}catch(t){e=!1}return function(){return e}}(),e.bindMediaToggle=function(t){function e(){t.media=a}var a=t.media||"all";t.addEventListener?t.addEventListener("load",e):t.attachEvent&&t.attachEvent("onload",e),setTimeout(function(){t.rel="stylesheet",t.media="only x"}),setTimeout(e,3e3)},e.poly=function(){if(!e.support())for(var a=t.document.getElementsByTagName("link"),n=0;n<a.length;n++){var o=a[n];"preload"!==o.rel||"style"!==o.getAttribute("as")||o.getAttribute("data-loadcss")||(o.setAttribute("data-loadcss",!0),e.bindMediaToggle(o))}},!e.support()){e.poly();var a=t.setInterval(e.poly,500);t.addEventListener?t.addEventListener("load",function(){e.poly(),t.clearInterval(a)}):t.attachEvent&&t.attachEvent("onload",function(){e.poly(),t.clearInterval(a)})}"undefined"!=typeof exports?exports.loadCSS=loadCSS:t.loadCSS=loadCSS}("undefined"!=typeof global?global:this);</script></head>

  <body>
    <div id="root">Loading ...</div>  
  <script type="text/javascript" src="0.b462a4b0ea0f53ce5925.js"></script><script type="text/javascript" src="5.fe98990a0cfe22bbeeb8.js"></script><script type="text/javascript" src="index.36d0a4091875de9b05d7.bundle.js"></script></body>

</html>
```

Thanks and let me know if you need any more info!

**Comment by thescientist13** [comment]
Thanks for the reply @papandreou !

Here is an upload of the build artifact I had generated prior to testing - [build.zip](https://github.com/Munter/subfont/files/2006712/build.zip)

For further context, the project is here and you can generate the same artificact by cloning it and running (if you already have Yarn installed)
1. `yarn install`
1. `yarn build`

Output will be in the _build/_ folder.

Thanks!

**Comment by papandreou** [comment]
@thescientist13, thanks! I can reproduce it.

The bug seems to be triggered by the same Google Web Font CSS being imported twice. You have `@import url(//fonts.googleapis.com/css?family=Josefin+Sans:300,400,400i,700|Josefin+Slab:300,400,400i,700);` in both index.html and unzip/build/0.ca7c27d106cde55c9e35.css

As a workaround you can remove one of the occurrences.

**Comment by papandreou** [comment]
Fixed in subfont 3.3.0. Thanks again for reporting it!

**Comment by thescientist13** [comment]
It's working, thanks so much @papandreou !

**Comment by Munter** [comment]
Looking at your page though, the subset probably only contains the characters for "loading", because that's the only static content subfont can pick up. If you want the entire content in the subset you will need to do a build time rendering of your page so all the content is available for analysis when subfont runs. This will also give you further speed improvements

**Comment by thescientist13** [comment]
Thanks @Munter !  I'll play around with this in a couple days and let you know how I make out.  I think having nice interop between this library and **critical** would be pretty awesome, so I'll see what I can do from my end to see what friction (if any) there may be.

Thanks again for all your help!
