### ISSUE TITLE
Multiple calls to subfont causing errors

### ISSUE THREAD

**Issue by m-allanson** [Munter/subfont#26]
I want to run subfont on just a few pages of a site:

```
/                         <-- run subfont on this index.html
  path-a/                 <-- run subfont on this index.html
    sub-path-1/
    sub-path-2/
    sub-path-3/
  path-b/                 <-- run subfont on this index.html
  path-c/
```

I run subfont three times, once for each path with `-r false`. It's running on build artifacts, so `-i` is used to modify the files in place. 

```
subfont /path/to/site/index.html -i -r false --inline-css --root file:///path/to/site
subfont /path/to/site/path-a/index.html -i -r false --inline-css --root file:///path/to/site
subfont /path/to/site/path-b/index.html -i -r false --inline-css --root file:///path/to/site
```

### Output

The second and third calls to subfont fail, the output for all three call looks like:

```
subfont /path/to/site/index.html -i -r false --inline-css --root file:///path/to/site
subfont /path/to/site/path-a/index.html -i -r false --inline-css --root file:///path/to/site
 ⚠ WARN: public/subfont/Font-A-500-f013aa502a.woff2: Command failed: pyftsubset /var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/input-11842-81883-ydqz9c.3dlvd.woff2 --output-file=/var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/output-11842-81883-lzwl1u.oo9g.woff2 --obfuscate_names --flavor=woff2 --text=" AGdeilsu" --no-ignore-missing-unicodes
         Traceback (most recent call last):
           File "/usr/local/bin/pyftsubset", line 11, in <module>
             sys.exit(main())
           File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
             return func(*args, **kwds)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3284, in main
             subsetter.subset(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3096, in subset
             self._subset_glyphs(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3043, in _subset_glyphs
             retain = table.subset_glyphs(self)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 1620, in subset_glyphs
             coverage.subset(glyphs)
         AttributeError: 'NoneType' object has no attribute 'subset'

 ⚠ WARN: public/subfont/Font-A-500-f013aa502a.woff2: Command failed: pyftsubset /var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/input-11842-81883-kx4mbz.ula.woff --output-file=/var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/output-11842-81883-ujakq3.sr25s.woff --obfuscate_names --flavor=woff --text=" AGdeilsu" --with-zopfli --no-ignore-missing-unicodes
         Traceback (most recent call last):
           File "/usr/local/bin/pyftsubset", line 11, in <module>
             sys.exit(main())
           File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
             return func(*args, **kwds)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3284, in main
             subsetter.subset(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3096, in subset
             self._subset_glyphs(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3043, in _subset_glyphs
             retain = table.subset_glyphs(self)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 1620, in subset_glyphs
             coverage.subset(glyphs)
         AttributeError: 'NoneType' object has no attribute 'subset'

 ⚠ WARN: public/subfont/Font-A-700-325abf0b35.woff2: Command failed: pyftsubset /var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/input-11842-81883-m04l9d.svi9.woff2 --output-file=/var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/output-11842-81883-vyzshm.yjkhr.woff2 --obfuscate_names --flavor=woff2 --text=" &.ACDEFGHIKLMNOPRSTUWYadeimnorsty" --no-ignore-missing-unicodes
         Traceback (most recent call last):
           File "/usr/local/bin/pyftsubset", line 11, in <module>
             sys.exit(main())
           File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
             return func(*args, **kwds)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3284, in main
             subsetter.subset(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3096, in subset
             self._subset_glyphs(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3043, in _subset_glyphs
             retain = table.subset_glyphs(self)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 1620, in subset_glyphs
             coverage.subset(glyphs)
         AttributeError: 'NoneType' object has no attribute 'subset'

 ⚠ WARN: public/subfont/Font-A-700-325abf0b35.woff2: Command failed: pyftsubset /var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/input-11842-81883-1sxv6lu.bri9g.woff --output-file=/var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/output-11842-81883-rg6zmn.h46xi.woff --obfuscate_names --flavor=woff --text=" &.ACDEFGHIKLMNOPRSTUWYadeimnorsty" --with-zopfli --no-ignore-missing-unicodes
         Traceback (most recent call last):
           File "/usr/local/bin/pyftsubset", line 11, in <module>
             sys.exit(main())
           File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
             return func(*args, **kwds)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3284, in main
             subsetter.subset(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3096, in subset
             self._subset_glyphs(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3043, in _subset_glyphs
             retain = table.subset_glyphs(self)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 1620, in subset_glyphs
             coverage.subset(glyphs)
         AttributeError: 'NoneType' object has no attribute 'subset'

 ⚠ WARN: public/subfont/Font-A-400-a2529a6186.woff2: Command failed: pyftsubset /var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/input-11842-81883-1cfh8hg.626wj.woff2 --output-file=/var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/output-11842-81883-1k4b13u.5g7z.woff2 --obfuscate_names --flavor=woff2 --text=" &'+,-.01278>?ABCDFGHILMNOPQRSTUWabcdefghiklmnopqrstuvwxyz©—’" --no-ignore-missing-unicodes
         Traceback (most recent call last):
           File "/usr/local/bin/pyftsubset", line 11, in <module>
             sys.exit(main())
           File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
             return func(*args, **kwds)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3284, in main
             subsetter.subset(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3096, in subset
             self._subset_glyphs(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3043, in _subset_glyphs
             retain = table.subset_glyphs(self)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 1620, in subset_glyphs
             coverage.subset(glyphs)
         AttributeError: 'NoneType' object has no attribute 'subset'

 ⚠ WARN: public/subfont/Font-A-400-a2529a6186.woff2: Command failed: pyftsubset /var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/input-11842-81883-w1s5kc.49owo.woff --output-file=/var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/output-11842-81883-16c3dcx.br98.woff --obfuscate_names --flavor=woff --text=" &'+,-.01278>?ABCDFGHILMNOPQRSTUWabcdefghiklmnopqrstuvwxyz©—’" --with-zopfli --no-ignore-missing-unicodes
         Traceback (most recent call last):
           File "/usr/local/bin/pyftsubset", line 11, in <module>
             sys.exit(main())
           File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
             return func(*args, **kwds)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3284, in main
             subsetter.subset(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3096, in subset
             self._subset_glyphs(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3043, in _subset_glyphs
             retain = table.subset_glyphs(self)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 1620, in subset_glyphs
             coverage.subset(glyphs)
         AttributeError: 'NoneType' object has no attribute 'subset'

subfont /path/to/site/path-b/index.html -i -r false --inline-css --root file:///path/to/site
 ⚠ WARN: public/subfont/Font-A-500-f013aa502a-1.woff2: Command failed: pyftsubset /var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/input-11842-81912-1668vnc.pv8m.woff2 --output-file=/var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/output-11842-81912-1ejlbl5.g3r.woff2 --obfuscate_names --flavor=woff2 --text=" AGdeilsu" --no-ignore-missing-unicodes
         Traceback (most recent call last):
           File "/usr/local/bin/pyftsubset", line 11, in <module>
             sys.exit(main())
           File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
             return func(*args, **kwds)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3284, in main
             subsetter.subset(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3096, in subset
             self._subset_glyphs(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3043, in _subset_glyphs
             retain = table.subset_glyphs(self)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 1620, in subset_glyphs
             coverage.subset(glyphs)
         AttributeError: 'NoneType' object has no attribute 'subset'

 ⚠ WARN: public/subfont/Font-A-500-f013aa502a-1.woff2: Command failed: pyftsubset /var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/input-11842-81912-1sgoiob.fkr6.woff --output-file=/var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/output-11842-81912-13cep4y.pelo.woff --obfuscate_names --flavor=woff --text=" AGdeilsu" --with-zopfli --no-ignore-missing-unicodes
         Traceback (most recent call last):
           File "/usr/local/bin/pyftsubset", line 11, in <module>
             sys.exit(main())
           File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
             return func(*args, **kwds)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3284, in main
             subsetter.subset(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3096, in subset
             self._subset_glyphs(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3043, in _subset_glyphs
             retain = table.subset_glyphs(self)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 1620, in subset_glyphs
             coverage.subset(glyphs)
         AttributeError: 'NoneType' object has no attribute 'subset'

 ⚠ WARN: public/subfont/Font-A-700-325abf0b35.woff2: Command failed: pyftsubset /var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/input-11842-81912-1qrol61.21dc.woff --output-file=/var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/output-11842-81912-17l0zxw.jh7r.woff --obfuscate_names --flavor=woff --text=" &.ACDEFGHIKLMNOPRSTUWYadeimnorsty" --with-zopfli --no-ignore-missing-unicodes
         Traceback (most recent call last):
           File "/usr/local/bin/pyftsubset", line 11, in <module>
             sys.exit(main())
           File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
             return func(*args, **kwds)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3284, in main
             subsetter.subset(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3096, in subset
             self._subset_glyphs(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3043, in _subset_glyphs
             retain = table.subset_glyphs(self)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 1620, in subset_glyphs
             coverage.subset(glyphs)
         AttributeError: 'NoneType' object has no attribute 'subset'

 ⚠ WARN: public/subfont/Font-A-700-325abf0b35.woff2: Command failed: pyftsubset /var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/input-11842-81912-2q06a.lu9qwx.woff2 --output-file=/var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/output-11842-81912-1kr7lr9.973pl.woff2 --obfuscate_names --flavor=woff2 --text=" &.ACDEFGHIKLMNOPRSTUWYadeimnorsty" --no-ignore-missing-unicodes
         Traceback (most recent call last):
           File "/usr/local/bin/pyftsubset", line 11, in <module>
             sys.exit(main())
           File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
             return func(*args, **kwds)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3284, in main
             subsetter.subset(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3096, in subset
             self._subset_glyphs(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3043, in _subset_glyphs
             retain = table.subset_glyphs(self)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 1620, in subset_glyphs
             coverage.subset(glyphs)
         AttributeError: 'NoneType' object has no attribute 'subset'

 ⚠ WARN: public/subfont/Font-A-400-a2529a6186.woff2: Command failed: pyftsubset /var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/input-11842-81912-ea1oid.w6j9h.woff2 --output-file=/var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/output-11842-81912-4gu01x.stoct.woff2 --obfuscate_names --flavor=woff2 --text=" &'+,-.01278>?ABCDFGHILMNOPQRSTUWabcdefghiklmnopqrstuvwxyz©—’" --no-ignore-missing-unicodes
         Traceback (most recent call last):
           File "/usr/local/bin/pyftsubset", line 11, in <module>
             sys.exit(main())
           File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
             return func(*args, **kwds)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3284, in main
             subsetter.subset(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3096, in subset
             self._subset_glyphs(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3043, in _subset_glyphs
             retain = table.subset_glyphs(self)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 1620, in subset_glyphs
             coverage.subset(glyphs)
         AttributeError: 'NoneType' object has no attribute 'subset'

 ⚠ WARN: public/subfont/Font-A-400-a2529a6186.woff2: Command failed: pyftsubset /var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/input-11842-81912-1l1f7yn.32ipk.woff --output-file=/var/folders/q4/rrk3h6ns2tgcb5jr2sxjn8j40000gn/T/output-11842-81912-xih5g2.rbyj.woff --obfuscate_names --flavor=woff --text=" &'+,-.01278>?ABCDFGHILMNOPQRSTUWabcdefghiklmnopqrstuvwxyz©—’" --with-zopfli --no-ignore-missing-unicodes
         Traceback (most recent call last):
           File "/usr/local/bin/pyftsubset", line 11, in <module>
             sys.exit(main())
           File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
             return func(*args, **kwds)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3284, in main
             subsetter.subset(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3096, in subset
             self._subset_glyphs(font)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3043, in _subset_glyphs
             retain = table.subset_glyphs(self)
           File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 1620, in subset_glyphs
             coverage.subset(glyphs)
         AttributeError: 'NoneType' object has no attribute 'subset'

```

If I rebuild the site, and only run the second or third call, they're successful. It looks like both of these calls are trying to modify the root html file `/path/to/site/index.html` which has already been modified by the first call. Is this expected behaviour? Is it possible to run subfont on a few individual pages within a site?

Running just `subfont /path/to/site/index.html -i --inline-css` works to subset the whole site.

### Expected output

subfont should run successfully.

**Comment by Munter** [comment]
Ouch, those are some nasty warnings. Haven't seen them before, so I don't have a quick fox for this one. Earliest time I'll have to look at it is next week.

I'm not entirely sure of the `-r false` behavior. Does `--no-recursive` make any difference in behavior? I'm wondering if it accidentally misunderstands that arguments and just recurses anyway.

Having subfont be idempotent would be nice. But that's probably very complex

**Comment by papandreou** [comment]
@m-allanson, are you able to share a tarball with the content of `/path/to/site/`? Then I'll take a look at it tonight.

**Comment by papandreou** [comment]
I guess it happens because subfont somehow chokes on its own output because `font-family: MyFont__subset, ...` gets spliced into the shared CSS after the first command has run, but the second page doesn't supply a definition for it because `@font-face { font-family: MyFont__subset; ... }` was only injected into an inline stylesheet in the first page.

@m-allanson, if that's the case, the below command should work:

```
subfont -i --no-recursive --inline-css --root file:///path/to/site \
  /path/to/site/index.html \
  /path/to/site/path-a/index.html \
  /path/to/site/path-b/index.html
```

**Comment by Munter** [comment]
I guess that would still create a shared subset across those pages. Usually that's not really a problem. Did we ever enable the per-page subsetting option? If I recall correctly it's mostly a matter of skipping the aggregation of the per-page subset data. The rest of the pipeline should re-do the work and hit caches if the work is the same

**Comment by papandreou** [comment]
> I guess that would still create a shared subset across those pages. Usually that's not really a problem. Did we ever enable the per-page subsetting option?

I don't think we did. I think we concluded that it wouldn't really be worth it, as it would almost always be better to expand the subset a bit and make the subset font cacheable across pages.

As far as I read understand this issue, @m-allanson doesn't necessarily want to create a subset font per page, it's just important that subfont is only applied to a few specific pages.

**Comment by m-allanson** [comment]
Thanks both for the help.

`--no-recursive` did not make any difference. I can't share the tarball for another day or so, but am happy to send it after that. 

> doesn't necessarily want to create a subset font per page, it's just important that subfont is only applied to a few specific pages.

Yep, exactly that. @papandreou's example of passing in multiple files was exactly what I needed, thank you!

I'll close this, but feel free to re-open if you want to further investigate the error from multiple subfont runs.
