### ISSUE TITLE
"this.from.parseTree.createElement is not a function" when running on the output of a previous subfont run

### ISSUE THREAD

**Issue by papandreou** [Munter/subfont#27]
While investigating #26 I ran into this:

```
$ subfont -o foo --inline-css --no-recursive https://webdevcph1.1prod.one/index.html
Guessing --root from input files: https://webdevcph1.1prod.one/
 ✔ 0.044 secs: logEvents
 ✔ 0.425 secs: loadAssets
 ⚠ WARN: https://webdevcph1.1prod.one/index.html: Asset is used as both Html and Image
 ✔ 3.917 secs: populate
 ✔ 0.017 secs: populate
 ✔ 0.092 secs: populate
 ✔ 4.821 secs: subsetFonts
 ✔ 0.005 secs: moveAssets
 ✔ 0.056 secs: writeAssetsToDisc
Output written to file:///home/andreas/work/subfont/foo/
$ subfont -i --inline-css --no-recursive foo/index.html 
Guessing --root from input files: file:///home/andreas/work/subfont/foo/
 ✔ 0.044 secs: logEvents
 ✔ 0.326 secs: loadAssets
 ⚠ WARN: foo/index.html: Asset is used as both Html and Image
 ✔ 4.870 secs: populate
 ✔ 0.055 secs: populate
 ✔ 0.114 secs: populate
TypeError: subsetFonts transform: this.from.parseTree.createElement is not a function
    at HtmlPreconnectLink.attach (/home/andreas/work/assetgraph/lib/relations/HtmlPreconnectLink.js:18:37)
    at JavaScript.addRelation (/home/andreas/work/assetgraph/lib/assets/Asset.js:1144:16)
    at asyncLoadStyleRelationWithFallback (/home/andreas/work/assetgraph/lib/transforms/subsetFonts.js:144:42)
    at subsetFonts (/home/andreas/work/assetgraph/lib/transforms/subsetFonts.js:980:11)
    at <anonymous>
```

**Comment by papandreou** [comment]
@Munter, another funky thing is that the index.html in the output of the first run ends up containing nested `<noscript>` tags. Here's a pretty print of the markup before `</body></html>`:

```html
<script>(function(){var el=document.createElement('link');el.href='https://fonts.googleapis.com/css?family=Roboto%20Slab%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%2Citalic%2Cregular&subset=all'.toString('url');el.rel='stylesheet';document.body.appendChild(el)}())</script>
<noscript>
   <link rel="preconnect" href="https://fonts.googleapis.com" crossorigin="anonymous">
   <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous">
   <script>(function(){var el=document.createElement('link');el.href='http://fonts.googleapis.com/css?family=Roboto%20Slab%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%2Citalic%2Cregular&subset=all'.toString('url');el.rel='stylesheet';document.body.appendChild(el)}())</script>
   <noscript>
      <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto%20Slab%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%2Citalic%2Cregular&amp;subset=all">
   </noscript>
</noscript>
<script>(function(){var el=document.createElement('link');el.href='https://fonts.googleapis.com/css?family=Roboto%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%2Citalic%2Cregular&subset=all'.toString('url');el.rel='stylesheet';document.body.appendChild(el)}())</script>
<noscript>
   <link rel="preconnect" href="https://fonts.googleapis.com" crossorigin="anonymous">
   <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous">
   <script>(function(){var el=document.createElement('link');el.href='http://fonts.googleapis.com/css?family=Roboto%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%2Citalic%2Cregular&subset=all'.toString('url');el.rel='stylesheet';document.body.appendChild(el)}())</script>
   <noscript>
      <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%2Citalic%2Cregular&amp;subset=all">
   </noscript>
</noscript>
```html

**Comment by Munter** [comment]
Looks like the noscript result from the first run, an inline html fragment with a Google font style sheet link tag, gets the full html file treatment
