### ISSUE TITLE
Using `--no-fallbacks` Option Throw Error

### ISSUE THREAD

**Issue by s0kil** [Munter/subfont#74]
```bash
> subfont __sapper__/export/index.html --in-place --inline-css --recursive --no-fallbacks

Guessing --root from input files: file:///home/sokil/Desktop/Projects/sokil-dev/__sapper__/export/
 ✔ 0.002 secs: logEvents
 ✔ 0.151 secs: loadAssets
 ✔ 0.400 secs: populate
 ✔ 0.001 secs: checkIncompatibleTypes
 ✔ 0.001 secs: populate
 ✔ 0.001 secs: populate
Create optimal font subsets from your actual font usage.
subfont [options] <htmlFile(s) | url(s)>

Options:
  --help                             Show help                                                                                                               [boolean]
  --version                          Show version number                                                                                                     [boolean]
  --root                             Path to your web root (will be deduced from your input files if not specified)                                           [string]
  --canonical-root, --canonicalroot  URI root where the site will be deployed. Must be either an absolute, a protocol-relative, or a root-relative url        [string]
  --output, -o                       Directory where results should be written to                                                                             [string]
  --fallbacks                        Include fallbacks so the original font will be loaded when dynamic content gets injected at runtime. Disable with --no-fallbacks
                                                                                                                                             [boolean] [default: true]
  --dynamic                          Also trace the usage of fonts in a headless browser with JavaScript enabled                            [boolean] [default: false]
  --in-place, -i                     Modify HTML-files in-place. Only use on build artifacts                                                [boolean] [default: false]
  --inline-fonts                     Inline fonts as data-URIs inside the @font-face declaration                                            [boolean] [default: false]
  --inline-css                       Inline CSS that declares the @font-face for the subset fonts                                           [boolean] [default: false]
  --font-display                     Injects a font-display value into the @font-face CSS. Valid values: auto, block, swap, fallback, optional
                                                                                 [string] [choices: "auto", "block", "swap", "fallback", "optional"] [default: "swap"]
  --formats                          Font formats to use when subsetting.                   [array] [choices: "woff2", "woff", "truetype"] [default: ["woff2","woff"]]
  --subset-per-page                  Create a unique subset for each page.                                                                  [boolean] [default: false]
  --recursive, -r                    Crawl all HTML-pages linked with relative and root relative links. This stays inside your domain       [boolean] [default: false]
  --silent, -s                       Do not write anything to stdout                                                                        [boolean] [default: false]
  --debug, -d                        Verbose insights into font glyph detection                                                             [boolean] [default: false]
  --dry-run, --dry, --dryrun         Don't write anything to disk                                                                           [boolean] [default: false]
TypeError: Cannot read property 'to' of undefined
    at subsetFonts (/home/sokil/Desktop/Projects/sokil-dev/node_modules/subfont/lib/subsetFonts.js:1325:64)
    at async subfont (/home/sokil/Desktop/Projects/sokil-dev/node_modules/subfont/lib/subfont.js:148:24)
```

**Comment by papandreou** [comment]
Thanks for reporting this bug! Fixed in 4.1.2.

**Comment by s0kil** [comment]
@papandreou Is the release automated?

**Comment by s0kil** [comment]
Nevermind, I noticed that NPM got a new release, but I was waiting for Github releases.
